
server:
  port: 9000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/kotlinblog?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true&useUnitcode=true&characterEncoding=utf8
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false

    properties:
      hibernate:
        default_batch_fetch_size: 100
        globally_quoted_identifiers: ture
    show-sql: true
